export const FETCH_QUESTION = 'FETCH_QUESTION';
export const QUESTION_LOADING='QUESTION_LOADING';
export const QUESTION_ERROR ='QUESTION_ERROR';
export const ADD_ANSWERS ='ADD_ANSWERS';
export const CORRECT_ANSWER_FOUND ='CORRECT_ANSWER_FOUND'